trigger:
  paths:
    include:
      - app/order-service/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  serviceConnection: 'aro-sp-connection'
  aksCluster: 'aks-onlinestore-dev-cac-001'
  aksResourceGroup: 'rg-onlinestore-dev-cac-001'
  aksServiceConnection: 'aro-sp-connection'
  acrName: 'acronlinestoredevcac001'
  namespace: 'default'
  environment: "dev"
  artifactName: 'manifests'
  imageTag: $(Build.BuildId)
  imageName: 'order'

stages:
  - stage: Build
    displayName: Build and Publish
    jobs:
      - job: BuildPublishDockerImages
        displayName: Build Publish Docker Images
        steps:
          # Docker is pre-installed on ubuntu-latest agents
          #- task: DockerInstaller@0
          #  displayName: Install Docker
          #  inputs:
          #    dockerVersion: '20.10.24'

          - template: appTemplates/build.yml
            parameters:
              serviceConnection: $(serviceConnection)
              acrName: $(acrName)
              imageName: $(imageName)
              dockerFilePath: '$(Build.sourcesdirectory)/app/order-service/Dockerfile'
              tag: $(imageTag)

          - task: PublishPipelineArtifact@1
            displayName: Publish Manifest
            inputs:
              artifactName: $(artifactName)
              path: $(artifactName)

  - stage: Deploy
    jobs:
      - deployment: DeployAKS
        displayName: Deploy AKS
        environment: $(environment)
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: $(artifactName)

                - script: |
                    echo "Workspace Directory: $(Pipeline.Workspace)"
                    ls -R "$(Pipeline.Workspace)"

                - task: AzureCLI@2
                  displayName: Get AKS Credentials and Deploy
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      echo "Getting AKS credentials..."
                      az aks get-credentials --name $(aksCluster) --resource-group $(aksResourceGroup) --overwrite-existing

                      echo "Updating deployment files with image tags..."
                      sed -i "s|acronlinestoredevcac001.azurecr.io/order|$(acrName).azurecr.io/order:$(imageTag)|g" $(Pipeline.Workspace)/manifests/order-deployment.yml

                      echo "Deploying to AKS..."
                      kubectl apply -f $(Pipeline.Workspace)/manifests/order-deployment.yml -n $(namespace)
                      kubectl apply -f $(Pipeline.Workspace)/manifests/order-service.yml -n $(namespace)

                      echo "Deployment completed."
