parameters:
- name: "serviceConnection"
  type: string
- name: "acrName"
  type: string
- name: "imageName"
  type: string
- name: "dockerFilePath"
  type: string
- name: "tag"
  type: string

steps:      
  - task: AzureCLI@2
    displayName: Build and publish ${{parameters.imageName}} to ACR
    inputs:
      azureSubscription: ${{parameters.serviceConnection}}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Building and pushing image: ${{parameters.imageName}}:${{parameters.tag}}"
        az acr build \
          --registry ${{parameters.acrName}} \
          --image ${{parameters.imageName}}:${{parameters.tag}} \
          --file ${{parameters.dockerFilePath}} \
          .